// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package family.domain;

import family.domain.Sex;

privileged aspect Person_Roo_JavaBean {
    
    public Sex Person.getSex() {
        return this.sex;
    }
    
    public void Person.setSex(Sex sex) {
        this.sex = sex;
    }
    
}
